In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings

In [3]:
dataKR = pd.read_csv('KRmatch.csv', index_col=[0])
dataKR

,d_spell,f_spell,champion,side,role,assists,damage_objectives,damage_building,damage_turrets,deaths,...,kda,kills,level,time_cc,damage_total,damage_taken,total_minions_killed,turret_kills,vision_score,result
0,14,4,Leona,Side.blue,Lane.utility,6,0,0,0,6,...,1.333333,2,9,23,15214,9404,36,0,47,False
1,11,4,Udyr,Side.red,Lane.jungle,8,547,46480,547,3,...,6.666667,12,16,32,194463,25782,23,1,20,True
2,14,4,Xerath,Side.red,Lane.utility,2,168,444,168,7,...,0.285714,0,10,22,34038,14079,26,0,38,False
3,14,4,Zoe,Side.red,Lane.mid_lane,8,2492,3082,2492,3,...,5.000000,7,14,29,94369,11128,133,2,17,True
4,4,12,Camille,Side.red,Lane.top_lane,8,6419,7408,6419,5,...,4.200000,13,15,25,110580,20404,141,2,24,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5692,12,4,Vex,Side.red,Lane.mid_lane,18,1361,12122,1361,6,...,4.166667,7,16,39,140108,20916,174,0,14,False
5693,4,7,Ezreal,Side.red,Lane.bot_lane,10,2097,21663,2097,14,...,1.285714,8,18,3,275357,35430,253,0,41,False
5694,12,4,Jayce,Side.red,Lane.top_lane,3,3426,5433,3426,4,...,1.500000,3,13,4,99117,10839,169,1,18,True
5695,4,11,Nidalee,Side.red,Lane.jungle,6,1249,15882,1249,2,...,7.500000,9,11,5,100611,14168,22,1,19,True
5696,11,4,LeeSin,Side.blue,Lane.jungle,18,3790,25410,3790,9,...,2.888889,8,17,22,191075,48117,60,2,52,True

In [4]:
dataKR['champion'].value_counts()

Jhin       218
LeeSin     214
Graves     205
Yone       151
Caitlyn    143
          ...
Gnar         1
Fizz         1
Brand        1
Ivern        1
Rammus       1
Name: champion, Length: 148, dtype: int64